name: Daily HIT Script Run

on:
  schedule:
    - cron: '15 0 * * *'  # UTC 00:15 = HKT 08:15
  workflow_dispatch:  # 手動觸發

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'
          install-chromedriver: true
      - name: Install Python dependencies
        run: pip install selenium
      - name: Run Script
        env:
          SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
          ZOHO_PASSWORD: ${{ secrets.ZOHO_PASSWORD }}
        run: python daily_export.py
