name: Run Download Housekeep

on:
  workflow_dispatch:

jobs:
  download-housekeep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Install Chromium and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y chromedriver

    - name: Run download_housekeep.py
      env:
        SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
      run: python download_housekeep.py
