name: Download CPLUS Files

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.wdm  # WebDriver Manager 緩存
            ~/chromium-bin  # 自定義目錄儲存 chromium 相關文件
          key: ${{ runner.os }}-pip-chromium-wdm-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-chromium-wdm-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir selenium webdriver-manager
          # 檢查並安裝或複製 chromium 相關文件
          mkdir -p ~/chromium-bin
          if [ ! -f ~/chromium-bin/chromium-browser ] || [ ! -f ~/chromium-bin/chromedriver ]; then
            sudo apt-get update -qq || true
            sudo apt-get install -y chromium-browser chromium-chromedriver || true
            cp /usr/bin/chromium-browser ~/chromium-bin/
            cp /usr/bin/chromedriver ~/chromium-bin/
          fi

      - name: Run Download Script
        env:
          SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
          ZOHO_EMAIL: ${{ secrets.ZOHO_EMAIL }}
          ZOHO_PASSWORD: ${{ secrets.ZOHO_PASSWORD }}
        run: python download_cplus.py
