name: Download Housekeep Reports

on:
  schedule:
    - cron: '15 0 * * *'  # UTC 00:15 = HKT 08:15
  workflow_dispatch:  # 支援手動觸發

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium
          sudo apt-get update -qq
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run Download Script
        env:
          SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
          ZOHO_EMAIL: ${{ secrets.ZOHO_EMAIL }}
          ZOHO_PASSWORD: ${{ secrets.ZOHO_PASSWORD }}
        run: python download_housekeep.py

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4  # 更新至 v4
        if: always()
        with:
          name: housekeep-report-html
          path: housekeep_report_html.txt
