name: CPLUS & BARGE Daily
on:
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.wdm
          key: ${{ runner.os }}-pip-chromium-wdm-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-chromium-wdm-
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install --no-cache-dir selenium webdriver-manager pytz
          sudo apt-get update -qq
          sudo apt-get install -y chromium-browser chromium-chromedriver xvfb
      - name: Set timezone to HKT
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime
          sudo sh -c 'echo "Asia/Hong_Kong" > /etc/timezone'
      - name: Verify timezone
        run: date
      - name: Run Download Script
        env:
          SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
          ZOHO_EMAIL: ${{ secrets.ZOHO_EMAIL }}
          ZOHO_PASSWORD: ${{ secrets.ZOHO_PASSWORD }}
          BARGE_PASSWORD: ${{ secrets.BARGE_PASSWORD }}
        run: xvfb-run --auto-servernum python CPLUS_&_BARGE_DAILY.py  # 用 xvfb-run 跑 python，讓 headless 有 display
      - name: Upload artifacts # 新加步驟
        if: always() # 即使失敗都上傳
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            *.png
            *.html
            *.txt # 上傳 screenshot, html, logs
