name: Download CPLUS Files

on:
  schedule:
    - cron: '15 7 * * *'  # UTC 07:15 = HKT 15:15
  workflow_dispatch:  # 支援手動觸發

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium
          sudo apt-get update -qq
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Check current time
        run: echo "Current UTC time: $(date -u), HKT time: $(date)"

      - name: Run Download Script
        env:
          SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
          ZOHO_EMAIL: ${{ secrets.ZOHO_EMAIL }}
          ZOHO_PASSWORD: ${{ secrets.ZOHO_PASSWORD }}
        run: python download_cplus.py

      - name: Add debug step
        run: echo "Workflow triggered at $(date -u)"
