name: Run Download Housekeep

on:
  workflow_dispatch:

jobs:
  download-housekeep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.wdm
        key: ${{ runner.os }}-pip-wdm-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-wdm-

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --no-cache-dir selenium webdriver-manager pytz
        sudo apt-get update -qq
        sudo apt-get install -y chromium-browser libnss3 libfontconfig1 libx11-6 libxcomposite1 libxcursor1 libxi6 libxtst6 libxrandr2
        sudo snap install chromium
        ls -l /snap/bin/chromium
        chromium-browser --version || true
        python -m webdriver_manager.chrome --driver_path /home/runner/chromium-bin/chromedriver
        sudo chmod +x /home/runner/chromium-bin/chromedriver
        ls -l /home/runner/chromium-bin/

    - name: Set timezone to HKT
      run: |
        sudo ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime
        sudo sh -c 'echo "Asia/Hong_Kong" > /etc/timezone'

    - name: Verify timezone
      run: date

    - name: Run download_housekeep.py
      env:
        SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
      run: python download_housekeep.py
