name: Run Download Housekeep

on:
  workflow_dispatch:

jobs:
  download-housekeep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/chromium-bin
        key: ${{ runner.os }}-pip-chromium-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-chromium-

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # 與 download_cplus.yml 一致

    - name: Install dependencies
      run: |
        pip install --no-cache-dir selenium pytz
        sudo apt-get update -qq
        sudo apt-get install -y chromium-browser chromium-chromedriver libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1
        mkdir -p ~/chromium-bin
        sudo cp /usr/bin/chromium-browser ~/chromium-bin/ || true
        sudo cp /usr/lib/chromium-browser/chromedriver ~/chromium-bin/ || true
        sudo chmod +x ~/chromium-bin/chromium-browser ~/chromium-bin/chromedriver
        ls -l ~/chromium-bin/

    - name: Set timezone to HKT
      run: |
        sudo ln -sf /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime
        sudo sh -c 'echo "Asia/Hong_Kong" > /etc/timezone'

    - name: Verify timezone
      run: date

    - name: Run download_housekeep.py
      env:
        SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
      run: python download_housekeep.py
