name: Download CPLUS Files

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            /usr/bin/chromium-browser
            /usr/bin/chromedriver
            ~/.wdm
          key: ${{ runner.os }}-pip-chromium-wdm-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-chromium-wdm-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir selenium webdriver-manager
          sudo apt-get update -qq || true
          sudo apt-get install -y chromium-browser chromium-chromedriver || true

      - name: Run Download Script
        env:
          SITE_PASSWORD: ${{ secrets.SITE_PASSWORD }}
          ZOHO_EMAIL: ${{ secrets.ZOHO_EMAIL }}
          ZOHO_PASSWORD: ${{ secrets.ZOHO_PASSWORD }}
        run: python download_cplus.py
