name: Trigger Colab with colabctl

on:
workflow_dispatch:  # 只支援手動觸發

jobs:
run-colab:
runs-on: ubuntu-latest
steps:

uses: actions/checkout@v4
name: Set up Python uses: actions/setup-python@v5 with: python-version: '3.9'
name: Install colabctl
run: pip install colabctl
name: Run Colab 
run: colabctl.py
run 'https://colab.research.google.com/drive/1BbJxRsYnrlHi_RN9zspiErEh3NAf9n83#scrollTo=Ny-t6BiW_3kz&line=1&uniqifier=1
