name: Trigger Colab with colabctl

on:
  workflow_dispatch:  # 只支援手動觸發（測試用，成功後加 schedule）

jobs:
  run-colab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install colabctl
        run: |
          python -m pip install --upgrade pip
          pip install colabctl
          colabctl --version || echo "colabctl installation failed"

      - name: Run Colab
        id: run-colab
        run: |
          echo "Attempting to run Colab notebook..."
          colabctl.py run 'https://colab.research.google.com/drive/1BbJxRsYnrlHi_RN9zspiErEh3NAf9n83' --verbose
          sleep 5  # 延遲 5 秒確保觸發
        continue-on-error: true

      - name: Check Output
        run: |
          echo "Run status: ${{ steps.run-colab.outcome }}"
          if [ "${{ steps.run-colab.outcome }}" == "failure" ]; then
            echo "Colab run failed, check logs for details."
            exit 1
          fi
