name: Trigger Colab with colabctl

on:
  schedule:
    - cron: '15 0 * * *'  # UTC 00:15 = HKT 08:15
  workflow_dispatch:  # 支援手動觸發

jobs:
  run-colab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install colabctl
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/bitnom/colabctl.git
          export PATH=$PATH:$(python -m site --user-base)/bin
          colabctl --version || echo "colabctl installation failed"

      - name: Run Colab
        run: |
          echo "Attempting to run Colab notebook..."
          # 直接運行 colabctl 並傳遞 URL 作為參數，忽略 notebooks.csv
          python -m colabctl run --url 'https://colab.research.google.com/drive/1BbJxRsYnrlHi_RN9zspiErEh3NAf9n83' --timeout 60 --verbose
