name: Trigger Colab with colabctl

on:
  schedule:
    - cron: '15 0 * * *'  # UTC 00:15 = HKT 08:15
  workflow_dispatch:  # 支援手動觸發

jobs:
  run-colab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install colabctl
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/bitnom/colabctl.git
          # 檢查安裝路徑並添加可執行文件
          export PATH=$PATH:$(python -m site --user-base)/bin
          colabctl --version || echo "colabctl installation failed or not executable"

      - name: Run Colab
        run: |
          # 用 Python 模塊方式運行 colabctl
          python -m colabctl run 'https://colab.research.google.com/drive/1BbJxRsYnrlHi_RN9zspiErEh3NAf9n83' --verbose
