name: Trigger Colab with colabctl

on:
  schedule:
    - cron: '15 0 * * *'  # UTC 00:15 = HKT 08:15
  workflow_dispatch:  # 支援手動觸發

jobs:
  run-colab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/bitnom/colabctl.git
          pip install selenium==4.9.0  # 指定 Selenium 版本，兼容舊 API
          sudo apt-get update -qq
          sudo apt-get install -y chromium-browser chromium-chromedriver
          export PATH=$PATH:/usr/lib/chromium-browser:/usr/bin
          export CHROMEDRIVER_PATH=/usr/bin/chromedriver
          colabctl --version || echo "colabctl installation failed"

      - name: Run Colab
        run: |
          echo "Attempting to run Colab notebook..."
          python -m colabctl run 60 'https://colab.research.google.com/drive/1BbJxRsYnrlHi_RN9zspiErEh3NAf9n83' --verbose
